LICENSE

feat: change LICENSE

---

i18n/zh/docusaurus-theme-classic/footer.json

feat: add footer i18n

---

docs/concepts/observability/metrics.md
docs/contribute/development-guide/development.md
docs/contribute/development-guide/plugin-builder.md
docs/contribute/development-guide/plugin.md
docs/contribute/development-guide/test-guide.md
i18n/zh/docusaurus-plugin-content-docs/current/concepts/observability/metrics.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/development-guide/development.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/development-guide/plugin-builder.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/development-guide/plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/development-guide/test-guide.md

Signed-off-by: 赵安家 <anjia0532@gmail.com>
1. metrics
2. development guide

docs: add metrics development guide docs

---

docs/concepts/terminology/manager.md
docs/reference/manage-console.md
i18n/zh/docusaurus-plugin-content-docs/current/concepts/terminology/manager.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/manage-console.md

docs: add manager console

---

docs/others/FAQs.md
i18n/zh/docusaurus-plugin-content-docs/current/others/FAQs.md

Add "Resources lacked" situation in FAQ

[docs] Add a situation in FAQ

---

docs/setup/integration/harbor.md
i18n/zh/docusaurus-plugin-content-docs/current/setup/integration/harbor.md

- Dragonfly integrated harbor.

docs: dragonfly integrated harbor

---

docs/others/FAQs.md
docs/reference/cli/manager.md
docs/reference/configuration/manager.md
docs/reference/configuration/scheduler.md
docs/setup/install/source.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/manager.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/manager.md
i18n/zh/docusaurus-plugin-content-docs/current/setup/install/source.md

fix: config link

---

docs/contribute/development-guide/plugin-builder.md
docs/contribute/development-guide/plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/development-guide/plugin-builder.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/development-guide/plugin.md

docs: add plugin develop guide

---

docs/concepts/observability/metrics.md
docs/concepts/observability/prometheus.md
i18n/zh/docusaurus-plugin-content-docs/current/concepts/observability/metrics.md
i18n/zh/docusaurus-plugin-content-docs/current/concepts/observability/prometheus.md

docs: update metrics

---

docs/setup/integration/harbor.md
docs/setup/integration/nydus.md
i18n/zh/docusaurus-plugin-content-docs/current/setup/integration/harbor.md
i18n/zh/docusaurus-plugin-content-docs/current/setup/integration/nydus.md

docs: add nydus

---

docs/concepts/observability/metrics.md
docs/reference/cli/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/concepts/observability/metrics.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/dfdaemon.md

- Change dfget daemon to dfdaemon.

docs: change dfget daemon to dfdaemon

---

docs/concepts/best-practices.md
docusaurus.config.js
i18n/zh/docusaurus-plugin-content-docs/current/concepts/best-practices.md
i18n/zh/docusaurus-theme-classic/footer.json
sidebars.js

docs: remove best practices

---

.github/workflows/docsearch.yml
docsearch.json
docusaurus.config.js
i18n/zh/code.json
i18n/zh/docusaurus-theme-classic/footer.json

feat: add docsearch

---

.github/workflows/docsearch.yml
docsearch.json
docusaurus.config.js

- Add docsearch for `netlify`.

feat: docsearch

---

docs/others/Roadmap.md
i18n/zh/docusaurus-plugin-content-docs/current/others/Roadmap.md

docs: update console roadmap

---

docs/setup/upgrade.md
i18n/zh/docusaurus-plugin-content-docs/current/setup/upgrade.md

Signed-off-by: ShuYingya <shuyingya@gmail.com>

[docs] Add dragonfly upgrade description

---

docs/concepts/terminology/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/concepts/terminology/dfdaemon.md

Signed-off-by: Jim Ma <majinjing3@gmail.com>

docs: update dfdaemon

---

docs/others/Roadmap.md
docs/setup/upgrade.md
i18n/zh/docusaurus-plugin-content-docs/current/others/Roadmap.md

docs: add dfdaemon roadmap

---

i18n/zh/docusaurus-plugin-content-docs/current.json
sidebars.js

docs: remove katacoda

---

docs/reference/configuration/dfdaemon.md
docs/reference/configuration/scheduler.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/scheduler.md

fix: config

---

docs/reference/configuration/cdn.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/cdn.md

Signed-off-by: 孙伟鹏 <weipeng.swp@alibaba-inc.com>
fix cdn config

Fix CDN config

---

i18n/zh/code.json
i18n/zh/docusaurus-theme-classic/footer.json
src/pages/index.js

- Landing page add ecosystem about harbor and nydus.

feat: landing page add ecosystem about harbor and nydus

---

docusaurus.config.js
i18n/zh/docusaurus-theme-classic/navbar.json
src/css/custom.css

feat: change navbar

---

docs/concepts/observability/metrics.md
i18n/zh/docusaurus-plugin-content-docs/current/concepts/observability/metrics.md

- Add type to task failed metrics.

feat: add type to task failed metrics

---

docusaurus.config.js

chore: add keywords to meta

---

docs/reference/cli/cdn.md
docs/reference/cli/dfdaemon.md
docs/reference/cli/manager.md
docs/reference/cli/scheduler.md
docs/reference/configuration/scheduler.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/cdn.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/manager.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/cli/scheduler.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/scheduler.md

docs: update command

---

docsearch.json

- Update docsearch website address.

feat: update docsearch website address

---

docs/getting-started/quick-start/docker-compose.md
docs/reference/preheat/api.md
i18n/zh/docusaurus-plugin-content-blog/2019-03-25-d7y-dfdaemon/index.md
i18n/zh/docusaurus-plugin-content-blog/2022-02-14-d7-jib/index.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/quick-start/docker-compose.md
i18n/zh/docusaurus-plugin-content-docs/current/others/FAQs.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/preheat/api.md

- Remove `dragonflyoss/Dragonfly2/docs`.

feat: remove dragonflyoss/Dragonfly2/docs

---

i18n/zh/docusaurus-plugin-content-docs/current.json
sidebars.js

chore: rename katacoda sidebar

---

.github/workflows/docsearch.yml

- Remove crawl on pull request.

chore: remove crawl on pull request

---

docs/contribute/development-guide/plugin-builder.md
docs/contribute/development-guide/plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/development-guide/plugin-builder.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/development-guide/plugin.md

Signed-off-by: Jim Ma <majinjing3@gmail.com>

docs: in-tree plugin

---

blog/2022-06-06-evolution-of-nydus/index.md
i18n/zh/docusaurus-plugin-content-blog/2022-06-06-evolution-of-nydus/index.md

Fix some typographical errors of article "The Evolution of the Nydus
Image Acceleration".
Signed-off-by: Jeffle Xu <jefflexu@linux.alibaba.com>

docs: fix typographical errors

---

docs/reference/configuration/manager.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/manager.md

- Add manager metrics enable field.

feat: add manager metrics enable field

---

blog/2022-06-06-evolution-of-nydus/index.md
i18n/zh/docusaurus-plugin-content-blog/2022-06-06-evolution-of-nydus/index.md

Signed-off-by: Jeffle Xu <jefflexu@linux.alibaba.com>

docs: add link to Nydus repository and user guide in the article

---

blog/2022-06-06-evolution-of-nydus/index.md

Signed-off-by: Gao Xiang <hsiangkao@linux.alibaba.com>

doc: fix a corrupted table in "The Evolution of the Nydus Image Acceleration"

---

docs/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.2/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.3/reference/configuration/dfdaemon.md
versioned_docs/version-v2.0.2/reference/configuration/dfdaemon.md
versioned_docs/version-v2.0.3/reference/configuration/dfdaemon.md

docs: dfdaemon add ns filter

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/dfdaemon.md

- Dfdaemon add piece download timeout.

docs: add piece download timeout

---

docs/setup/install/helm-charts.md
i18n/zh/docusaurus-plugin-content-docs/current/setup/install/helm-charts.md

- Add prerequisites to installation guide.

docs: add prerequisites to installation guide

---

i18n/zh/docusaurus-plugin-content-docs/current/concepts/terminology/scheduler.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.3/concepts/terminology/scheduler.md

fix: scheduler typo

---

docs/reference/configuration/manager.md

Update docs for manager config
Add new tls parameter (added in https://github.com/dragonflyoss/Dragonfly2/pull/1300) and rename tls parameter to tlsConfig.
https://github.com/dragonflyoss/Dragonfly2/issues/1299
This update to the documentation is required when https://github.com/dragonflyoss/Dragonfly2/pull/1300 is merged

Update docs for manager config

---

docs/contribute/development-guide/plugin.md
i18n/zh/docusaurus-plugin-content-docs/current/contribute/development-guide/plugin.md

- Update golang version to `1.18`.

feat: update golang version to 1.18

---

docs/reference/configuration/manager.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/manager.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.2/reference/configuration/manager.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.3/reference/configuration/manager.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.4/reference/configuration/manager.md
versioned_docs/version-v2.0.2/reference/configuration/manager.md
versioned_docs/version-v2.0.3/reference/configuration/manager.md
versioned_docs/version-v2.0.4/reference/configuration/manager.md

- Change manager local cache ttl.

feat: change manager local cache ttl

---

docs/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/dfdaemon.md

Signed-off-by: Jim Ma <majinjing3@gmail.com>

feat: concurrent option

---

docs/setup/install/source.md
i18n/zh/docusaurus-plugin-content-docs/current/setup/install/source.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.4/setup/install/source.md
versioned_docs/version-v2.0.4/setup/install/source.md

feat: remove nginx dependency

---

docs/reference/configuration/scheduler.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/scheduler.md

feat: scheduler adds data dir

---

docs/concepts/observability/metrics.md
docs/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/concepts/observability/metrics.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/dfdaemon.md

- Rename biz_tag to tag.
- Dfdaemon adds defaultTag config.

feat: rename biz_tag to tag

---

docs/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/dfdaemon.md

Signed-off-by: greenhandatsjtu <sunhengke@sjtu.edu.cn>

feat: add download speed threshold option for concurrent backsource

---

docs/reference/cli/dfstore.md

correct upload & download cmd of dfstore in Example doc

correct upload & download cmd of dfstore in example doc

---

docs/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/dfdaemon.md

add path for health config
#173

add path for health config

---

blog/2022-11-03-dragonfly-integrates-nydus-for-image-acceleration-practice/index.md
docs/getting-started/quick-start/kubernetes.md
docs/reference/configuration/dfdaemon.md
docs/setup/integration/nydus.md
docs/setup/integration/stargz.md
i18n/zh/docusaurus-plugin-content-blog/2022-11-03-dragonfly-integrates-nydus-for-image-acceleration-practice/index.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/quick-start/kubernetes.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/current/setup/integration/nydus.md
i18n/zh/docusaurus-plugin-content-docs/current/setup/integration/stargz.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.6/getting-started/quick-start/kubernetes.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.7/getting-started/quick-start/kubernetes.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.7/setup/integration/nydus.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.7/setup/integration/stargz.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.8/getting-started/quick-start/kubernetes.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.8/setup/integration/nydus.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.8/setup/integration/stargz.md
versioned_docs/version-v2.0.6/getting-started/quick-start/kubernetes.md
versioned_docs/version-v2.0.7/getting-started/quick-start/kubernetes.md
versioned_docs/version-v2.0.7/setup/integration/nydus.md
versioned_docs/version-v2.0.7/setup/integration/stargz.md
versioned_docs/version-v2.0.8/getting-started/quick-start/kubernetes.md
versioned_docs/version-v2.0.8/setup/integration/nydus.md
versioned_docs/version-v2.0.8/setup/integration/stargz.md

添加对helm部署dfdaemon时定义变量需要":"的提示。

docs: add tips for helm dfdaemon metrics value

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.6/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.7/reference/configuration/dfdaemon.md
i18n/zh/docusaurus-plugin-content-docs/version-v2.0.8/reference/configuration/dfdaemon.md

Signed-off-by: Tianxi <litianximail@qq.com>
fix: dfdaemon thresholdSize explain

fix: dfdaemon thresholdSize explain
